[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# (opcional) permitir ESM/externals si hace falta
[functions."send-push"]
  external_node_modules = ["web-push"]
