[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["web-push"]

# === Scheduled Functions ===
[[scheduled_functions]]
  path = "cron-check"      # netlify/functions/cron-check.ts
  schedule = "*/1 * * * *" # cada 1 minuto

[[scheduled_functions]]
  path = "cron-30m"        # netlify/functions/cron-30m.ts
  schedule = "*/30 * * * *" # cada 30 minutos


# Opcional: también podés dejar las funciones normales explícitas
# (Netlify detecta automáticamente, pero lo dejamos por claridad)
[functions."send-push"]
  external_node_modules = ["web-push"]
  node_bundler = "esbuild"

[functions."save-subscription"]
  node_bundler = "esbuild"

[functions."save-orders"]
  node_bundler = "esbuild"
