[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["web-push"]

[[scheduled.functions]]
  # corre cada minuto
  path = "check-prices"
  schedule = "*/1 * * * *"
